### ISSUE TITLE
Back feature

### ISSUE THREAD

**Issue by alkanna** [UgnisSoftware/react-spreadsheet-import#117]
Hello,

Are there any plans to support a "go back" feature ?
If so, would that be compatible with a router somehow with the browser back button ?

Would you be open to a pull request for the former feature only ?

Thanks !

**Comment by masiulis** [comment]
Hey @alkanna, feel free to open a PR for this.

We don't save previous step state anywhere, so that would need to be added, you can check the state each step expects here [https://github.com/UgnisSoftware/react-spreadsheet-import#initial-state](https://github.com/UgnisSoftware/react-spreadsheet-import#initial-state).

If you would like to add navigation when clicking on steps at the top, we use this stepper library [https://github.com/jeanverster/chakra-ui-steps#steps](https://github.com/jeanverster/chakra-ui-steps).

**Comment by rdmQI** [comment]
I can see that there is an open PR for this. Will this be merged anytime soon?

**Comment by bkuermayr** [comment]
Would also love to see this feature

**Comment by masiulis** [comment]
Released in 4.5.0 under prop `isNavigationEnabled`.
